### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/xtsentry/vendor/sentry/sentry/lib/Raven/Client.php on line 331

### ISSUE THREAD

**Issue by CeleritasCognito** [anibalsanchez/XT-Sentry-for-Joomla#2]
I am getting a: Deprecated: Array and string offset access syntax with curly braces is deprecated `/libraries/xtsentry/vendor/sentry/sentry/lib/Raven/Client.php on line 331`

is there a way to fix this?

**Comment by anibalsanchez** [comment]
It is just a notice. Something that is going to be dropped on PHP8. You can hide the notice now.

**Comment by anibalsanchez** [comment]
I'm going to update the library specs to the latest version.

**Comment by CeleritasCognito** [comment]
Thanks, I also saw that the current SDK used is deprecated. Will this also be updated?

**Comment by CeleritasCognito** [comment]
@anibalsanchez hey, I updated the framework myself to 2.4.1, but I have no idea how to make a pull request because I dont see how you generate the vendor files. Can I send you the files and you update the Github page?

**Comment by anibalsanchez** [comment]
Great news! I didn't find the time to do it.

The vendor files are not committed. If you send the updated `composer.json` in the PR then, we can regenerate the vendor at any time.

**Comment by CeleritasCognito** [comment]
Okay, PR is created. :)

**Comment by anibalsanchez** [comment]
Than you! PR merger. New version coming soon ;-)
